//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workforce.Data.Associates2.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateAddress
    {
        public int AssociateAddressID { get; set; }
        public int AssociateID { get; set; }
        public int AddressID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Associate Associate { get; set; }
    }
}
